spring:
  application:
    name: musicapi

openapi: 3.0.1
info:
  title: Music API
  version: v1
paths:
  /api/v1/albums:
    post:
      summary: Cadastrar Ã¡lbum
      responses:
        '201':
          description: Criado

  /api/v1/regionais:
    get:
      summary: Listar regionais ativas
      responses:
        '200':
          description: OK

  /api/v1/regionais/sincronizar:
    post:
      summary: Sincronizar regionais externas
      responses:
        '200':
          description: Sincronizado
